# gokaygurcan/dockerfile-ubuntu

language: bash
services: docker

sudo: false

git:
  depth: 1

before_script:
  - docker version
  - docker info

script:
  - docker build --rm -t gokaygurcan/ubuntu:test .
  - docker run --rm gokaygurcan/ubuntu:test /bin/bash --version

notifications:
  email: false
